# Goal
string message  # When method==action_server_video "true" will record data and "false" will pause recording
---
# Result
bool job_success  # True if the job was a success, False otherwise
---
# Feedback
string job_status  # More specific job information stored here
